version: '3'
services:
    client:
        build:
            dockerfile: Dockerfile.prod
        ports:
            - 8080:80
            # - 443:443
    api2:
        build:
            dockerfile: Dockerfile.prod
