version: '3'
services:
    client:
        build:
            dockerfile: Dockerfile.prod
        ports:
            - 8080:80
    api:
        build: ./src/api
        env_file:
            - .env
        volumes:
            - ./src/api:/api
            - /api/node_modules
        ports:
            - 8000:8000
        container_name: mini_app_api
        depends_on:
            - flyway
    flyway:
        image: boxfuse/flyway:5.2.1
        command: -url=jdbc:postgresql://db:5432/${DB_DATABASE} -schemas=public -user=${DB_USER} -password=${DB_PASSWORD} migrate
        volumes:
            - ./src/sql:/flyway/sql
        container_name: mini_app_flyway
        depends_on:
            - db
    db:
        image: postgres
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - 5432:5432
        container_name: mini_app_db
