version: '3'
services:
    client:
        build:
            context: ./src/client
        volumes:
            - ./src/client:/client
            - /client/node_modules
        tty: true
        container_name: ${CONTAINER_NAME_CLIENT}
        depends_on:
            - api
    api:
        build:
            context: ./src/api
        volumes:
            - ./src/api:/api
            - /api/node_modules
        container_name: ${CONTAINER_NAME_API}
        depends_on:
            - flyway
    flyway:
        image: boxfuse/flyway:5.2.1
        command: -url=jdbc:postgresql://db:5432/${DB_DATABASE} -schemas=public -user=${DB_USER} -password=${DB_PASSWORD} migrate
        volumes:
            - ./sql:/flyway/sql
        container_name: ${CONTAINER_NAME_FLYWAY}
        depends_on:
            - db
    db:
        image: postgres
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - 5432:5432
        container_name: ${CONTAINER_NAME_DB}
