version: '3'
services:
    client:
        ports:
            - 3000:3000
    api2:
        env_file:
            - .env
        ports:
            - 8001:8000
    api:
        env_file:
            - .env
        ports:
            - 8000:8000
