export const COLLAPSE_MENU = 'COLLAPSE_MENU';
export type COLLAPSE_MENU = typeof COLLAPSE_MENU;

export const COLLAPSE_TOGGLE = 'COLLAPSE_TOGGLE';
export type COLLAPSE_TOGGLE = typeof COLLAPSE_TOGGLE;

export const NAV_COLLAPSE_LEAVE = 'NAV_COLLAPSE_LEAVE';
export type NAV_COLLAPSE_LEAVE = typeof NAV_COLLAPSE_LEAVE;

export const NAV_CONTENT_LEAVE = 'NAV_CONTENT_LEAVE';
export type NAV_CONTENT_LEAVE = typeof NAV_CONTENT_LEAVE;
