# stage1 - build react app first
FROM node:12.16.1-alpine3.9 as build
WORKDIR /client
ENV PATH /client/node_modules/.bin:$PATH
COPY ./package.json /client/
RUN yarn --silent
COPY . /client
RUN yarn build

# stage 2 - build the final image and copy the react build files
FROM nginx:1.17.8-alpine
COPY --from=build /client/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]